# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0008_commentdatarule'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='molocomment',
            managers=[
            ],
        ),
    ]
