# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0009_auto_20180226_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentingsettings',
            old_name='commenting_anonymous_alias',
            new_name='commenting_anonymous',
        ),
    ]
